services:
  db:
    container_name: db
    image: mysql:9.5
    command: --pid-file=/var/lib/mysql-files/mysqld.pid
    # build:
    #   context: db
    #   dockerfile: db.Dockerfile
    ports:
      - "3306:3306"  # Port MySQL
    environment:
      - TZ=${TZ}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
      # - postgres_data:/var/lib/postgresql/data  # Volume persistant pour la base de données
      - ./db/my.conf:/etc/mysql/conf.d/my.conf
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: backend
      dockerfile: backend.Dockerfile
    ports:
      - "5000:5000"
    environment:
      # Globales
      - TZ=${TZ}
      - FLASK_ENV=${FLASK_ENV}
      # DB
      - DATABASE_URL=${DATABASE_URL}
      - ADMIN_NAME=${ADMIN_NAME}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - API_PATH_ROOT=${API_PATH_ROOT}
    volumes:
      # - ./backend/code:/app:ro
        - ./backend/code:/app
        - ./backend/tests:/app/tests
    networks:
      - frontend
      - backend
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - frontend
    environment:
      - TZ=${TZ}
      - API_URL=${API_URL}
      - SERVER_NAME=${SERVER_NAME}
    volumes:
      - ./frontend/code:/var/www/html
      - ./frontend/conf/apache2.conf:/etc/apache2/apache2.conf:ro
    depends_on:
      - backend

networks:
  frontend:
    driver: bridge  # Réseau pour la communication entre frontend et backend
  backend:
    driver: bridge  # Réseau isolé pour la communication entre backend et db

volumes:
  postgres_data:  # Volume persistant pour la base de données
