{{- if and .Values.cdn.autoscaling.enabled (not (empty .Values.cdn.autoscaling)) }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "winenot.fullname" . }}-cdn-hpa
  labels:
    {{- include "winenot.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "winenot.fullname" . }}-cdn
  minReplicas: {{ .Values.cdn.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.cdn.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.cdn.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
