apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "winenot.fullname" . }}-playwright
  labels:
    {{- include "winenot.labels" . | nindent 4 }}
    app.kubernetes.io/component: playwright
spec:
  replicas: {{ .Values.playwright.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "winenot.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: playwright
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "winenot.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: playwright
    spec:
      containers:
        - name: playwright
          image: "{{ .Values.playwright.image.repository }}{{ if .Values.playwright.image.tag }}:{{ .Values.playwright.image.tag }}{{ end }}"
          imagePullPolicy: {{ .Values.playwright.image.pullPolicy }}
          command:
            {{- toYaml .Values.playwright.command | nindent 12 }}
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: TZ
              value: {{ .Values.global.timezone | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
