{{- if .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "winenot.fullname" . }}-rolebinding
  labels:
    {{- include "winenot.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ default (include "winenot.fullname" .) .Values.serviceAccount.name | trunc 63 | trimSuffix "-" }}-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "winenot.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
