apiVersion: v1
kind: Secret
metadata:
  name: {{ include "winenot.fullname" . }}-secrets
  labels:
    {{- include "winenot.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_USER: {{ .Values.mysql.auth.user | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.auth.password | quote }}
  MYSQL_DATABASE: {{ .Values.mysql.auth.database | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.auth.rootPassword | quote }}
  ADMIN_NAME: {{ .Values.backend.env.adminName | quote }}
  ADMIN_USERNAME: {{ .Values.backend.env.adminUsername | quote }}
  ADMIN_PASSWORD: {{ .Values.backend.env.adminPassword | quote }}
