{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "winenot.fullname" .) .Values.serviceAccount.name | trunc 63 | trimSuffix "-" }}-sa
  labels:
    {{- include "winenot.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
